### ISSUE TITLE
A fix for inline Rust issues

### ISSUE THREAD

**Issue by RobertJacobsonCDC** [phoenixr-codes/mdbook-inline-highlighting#1]
People using this plugin with inline Rust might need to disable the Rust playground feature:

```toml
[output.html.playground]
runnable = false
```

Otherwise every inline piece of Rust is rendered as a block code element with Rust playground buttons—even if code-fenced Rust isn't.
